### ISSUE TITLE
Wrong Resource URI

### ISSUE THREAD

**Issue by waynegraham** [OpenGeoMetadata/edu.virginia#3]
Link to online resource is an old link that is redirected. Need to update http://www2.lib.virginia.edu/scholarslab/ to the correct address.

**Comment by adarwinian** [comment]
A UVa Lib Guide page already exists.

http://guides.lib.virginia.edu/content.php?pid=62214&sid=464804

**Comment by waynegraham** [comment]
Ran this update with

``` bash
find . -name "*.xml" -exec sed -i'' -e 's/www2.lib.virginia.edu\/scholarslab/guides.lib.virginia.edu\/content.php\?pid=62214\&amp;sid=464804/g' {} \;s
find . -name "*.xml-e" -print0 | xargs -0 rm -rf
```
