### ISSUE TITLE
Create JSON

### ISSUE THREAD

**Issue by waynegraham** [OpenGeoMetadata/edu.virginia#5]
Solr json documents need to be created for each layer as `geoblacklight.json` and remove the XML version of the file (`geoblacklight.xml`).

**Comment by waynegraham** [comment]
JSON docs were added in 1db6cb6fff5a638a219366f94a63c0128ad946b3, but contain nested elements. Need to update the XSLT.

**Comment by ammonshepherd** [comment]
JSON docs recreated (a number of times), most recently with a ruby script from @erochest to create them from the xml files.

**Comment by erochest** [comment]
This happened in 455c08c576c9e49735da00718aa8faae2e2f6564.
