### ISSUE TITLE
Missing Metadata in HTML fields

### ISSUE THREAD

**Issue by waynegraham** [OpenGeoMetadata/edu.virginia#7]
Many of the fields in the HTML version of the metadata are missing, only having links to the metadata definitions.

**Comment by ammonshepherd** [comment]
By "command technical decision" we are not including a link to the HTML files (not enough useful data in them). HTML files left in there for now. If we need to add them in the future, it will probably be best to either use the iso2json.rb file (in the geoblacklight-converter repo) or create a new script to generate HTML files. The HTML creator from GeoCombine leaves out too many fields.
